<ips:template parameters="$member, $player, $pdata, $stats, $advs, $statkeys" />

<ol class='ipsDataList'>
	<li class='ipsDataItem ipsClearfix ipsDataItem_unread'>
        <ul class='ipsDataItem_withPhoto ipsList_inline ipsDataItem_icon'>
			<li><a href='#' class='ipsUserPhoto ipsUserPhoto_mini ipsPos_left'><img src='https://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Ster_Orde_van_het_Britse_Rijk.jpg/220px-Ster_Orde_van_het_Britse_Rijk.jpg' alt=''></a></li>
		</ul>
		<div class='ipsDataItem_main'>
			<h4 class='ipsDataItem_title'>{$player->player_name}</h4>
			<p class='ipsDataItem_meta'>
				{$player->api_uuid}
			</p>
			<ul class='ipsDataItem_subList ipsList_inline'>
				<li class='ipsDataItem_unread'><a href='#'>&lt;Order of Saint Vicses&gt;</a> <span class='ipsBadge ipsBadge_positive
'>Guild Leader</span></li>
			</ul>
		</div>
	</li>
    <img src='https://crafatar.com/renders/body/{$player->player_uuid}?overlay' alt='{$player->player_name}' />
</ol>
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Main Advancements</h2>
<div class='ipsBox'>
<ol class='ipsDataList'>
    <ul class='ipsDataItem_subList ipsList_inline'>
        {{foreach $advs as $key => $value}}
            {{if is_array($value)}}
                {{if mb_substr($key, 0, 17) !== "minecraft:recipes"}}
                    {{if mb_substr($key, mb_strlen($key)-4,4) !== "root"}}
						{{if $value['done']}}
                        	<li>{$key}</li>
						{{endif}}
                    {{endif}}
                {{endif}}
            {{endif}}
        {{endforeach}}
    </ul>
</ol>
</div>
<h2 class="ipsType_sectionTitle ipsType_reset cForumTitle">Roleplay Progression</h2>
<div class='ipsBox'>
    <p>kek</p>
</div>


<!-- The tab bar -->
<div class='ipsTabs ipsClearfix' id='elTabBar' data-ipsTabBar data-ipsTabBar-contentArea='#elTabBar_content'>
	<a href='#elTabBar' data-action='expandTabs'><i class='icon-caret-down'></i></a>
	<ul role='tablist'>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftbroken' class='ipsTabs_item' aria-selected="true">
				{lang="$statkeys[0]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftkilled_by' class='ipsTabs_item'>
				{lang="$statkeys[1]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftkilled' class='ipsTabs_item'>
				{lang="$statkeys[2]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftmined' class='ipsTabs_item'>
				{lang="$statkeys[3]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftcustom' class='ipsTabs_item'>
				{lang="$statkeys[4]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftpicked_up' class='ipsTabs_item'>
				{lang="$statkeys[5]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftdropped' class='ipsTabs_item'>
				{lang="$statkeys[6]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftcrafted' class='ipsTabs_item'>
				{lang="$statkeys[7]"}
			</a>
		</li>
		<li role='presentation'>
			<a href='#' role='tab' id='elPlayerTab_minecraftused' class='ipsTabs_item'>
				{lang="$statkeys[8]"}
			</a>
		</li>
	</ul>
</div>



<!-- The tab panel wrapper -->
<section id="elTabBar_content" class="ipsTabs_panels ipsPad_double ipsAreaBackground_reset">
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftbroken_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="false">
		{{foreach $stats['stats']['minecraft:killed'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftkilled_by_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:broken'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftkilled_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:used'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftmined_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:picked_up'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftcustom_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:killed_by'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftpicked_up_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:custom'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftdropped_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:crafted'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftcrafted_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:dropped'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
	<div id='ipsTabs_elTabBar_elPlayerTab_minecraftused_panel' class="ipsTabs_panel ipsAreaBackground_reset" aria-hidden="true">
		{{foreach $stats['stats']['minecraft:mined'] as $stat => $count}}
			<p>{$stat}:{$count}</p>
		{{endforeach}}
	</div>
</section>

	
