<?php

$lang = array(
	'__app_everpanel'	=> "EverPanel",
	'frontnavigation_everpanel' => "EverPanel",
	'frontnavigation_everpanel_settings' => "Profile Settings",
	'memberACPProfileTitle_everpanel_Main' => "Minecraft Profile",
	'memberACPProfileLink_everpanel_Info' => "Info",
	'memberACPProfileLink_everpanel_Access' => "Access",
	'ep_name' => "Minecraft IGN",
	'ep_uuid' => "Name",
	'ep_settings_blurb' => "Manage your Minecraft IGN. You will only be able to set this once!",
	'ep_settings' => "Minecraft Profile Settings",
	'editname' => "Edit IGN",
	'overview' => "Overview",
	'module__everpanel_name' => "Change Name",
	'module__everpanel_name_blurb' => "Change your IGN and your UUID will be validated.",
	'unknown' => "Unknown",
	'module__everpanel_profile' => "Minecraft Profile",
	'menu_player_profile' => "My Player Profile",
	'minecraft:broken' => "Blocks Broken",
	'minecraft:killed_by' => "Mobs Killed By",
	'minecraft:killed' => "Mobs Killed",
	'minecraft:mined' => "Blocks Mined",
	'minecraft:custom' => "Misc.",
	'minecraft:picked_up' => "Items picked up",
	'minecraft:dropped' => "Items Dropped",
	'minecraft:crafted' => "Items crafted",
	'minecraft:used' => "Items used",
);
