<ips:template parameters="$player" />
<div class='ipsColumns ipsColumns_collapsePhone'>
	<div class='ipsColumn ipsColumn_fluid'>
		<ul class='ipsDataList'>
            <li class='ipsDataItem'>
				<div class='ipsDataItem_main'>
                    <h4 class='ipsDataItem_title'><strong>{lang="ep_name"}</strong></h4><br>
                    {$player->player_name}
                </div>
            </li>
            <li class='ipsDataItem'>
                <div class='ipsDataItem_main'>
                    <h4 class='ipsDataItem_title'><strong>{lang="ep_uuid"}</strong></h4><br>
                    {$player->player_uuid}
                </div>
            </li>
        </ul>
    </div>
</div>