<ips:template parameters="$tab, $output" />
{template="pageHeader" group="global" app="core" params="\IPS\Member::loggedIn()->language()->addToStack('ep_settings'), \IPS\Member::loggedIn()->language()->addToStack('ep_settings_blurb')"}
<div class='ipsBox ipsBox_transparent ipsAreaBackground' id='elSettingsTabs' data-ipsTabBar data-ipsTabBar-contentArea='#elProfileTabContent' data-ipsTabBar-itemSelector='.ipsSideMenu_item' data-ipsTabBar-activeClass='ipsSideMenu_itemActive'>
	<div class='ipsColumns ipsColumns_collapsePhone ipsColumns_bothSpacing'>
		<div class='ipsColumn ipsColumn_wide'>
			<div class='ipsSideMenu' data-ipsSideMenu>
				<h3 class="ipsSideMenu_mainTitle ipsAreaBackground_light ipsType_medium">
					<a href="#modcp_menu" class="ipsPad_double" data-action="openSideMenu">
						<i class="fa fa-bars"></i> &nbsp;{lang="settings_area"}&nbsp;<i class="fa fa-caret-down"></i>
					</a>
				</h3>
				<ul class="ipsSideMenu_list">
					<li>
						<a href='{url="app=everpanel&module=system&controller=settings" seoTemplate="settings"}' id='setting_overview' class='ipsType_normal ipsSideMenu_item {{if $tab === 'overview'}}ipsSideMenu_itemActive{{endif}}' title="{lang="overview"}" role="tab" aria-selected="{{if $tab === 'overview'}}true{{else}}false{{endif}}">
							<i class='fa fa-tachometer'></i> {lang="overview"}
						</a>
                    </li>
                    <li>
						<a href='{url="app=everpanel&module=system&controller=settings&area=name" seoTemplate="settings_name"}' id='setting_name' class='ipsType_normal ipsSideMenu_item {{if $tab === 'editname'}}ipsSideMenu_itemActive{{endif}}' title="{lang="editname"}" role="tab" aria-selected="{{if $tab === 'name'}}true{{else}}false{{endif}}">
							<i class='fa fa-wrench'></i> {lang="editname"}
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class='ipsColumn ipsColumn_fluid'>
			<section id='elProfileTabContent' class='ipsBox ipsPad'>
				<div id="ipsTabs_elSettingsTabs_setting_{$tab}_panel" class="ipsTabs_panel" aria-labelledby="setting_overview" aria-hidden="false">
					{$output|raw}
				</div>
			</section>
		</div>
	</div>
</div>