<ips:template parameters="$member"/>
<div class="acpMemberView_info ipsBox ipsSpacer_bottom ipsSpacer_double">
    <h2 class='ipsBox_titleBar ipsType_reset'>
        Player Info
        {{if member.hasAcpRestriction( 'core', 'members', 'member_edit' ) and ( !$member->isAdmin() or ( member.hasAcpRestriction( 'core', 'members', 'member_edit_admin' ) and  member.hasAcpRestriction( 'core', 'members', 'member_move_admin1' ) ) )}}
			<a href="{url="app=everpanel&module=members&controller=members&do=editBlock&block=IPS\\core\\extensions\\core\\MemberACPProfileBlocks\\Groups&id={$member->member_id}"}" class="ipsPos_right ipsType_medium" data-ipsDialog data-ipsDialog-title="{lang="memberACPProfileLink_everpanel_Info"}">{lang="edit"}</a>
		{{endif}}
    </h2>
    <div class='ipsPad ipsClearfix'>
        Player IGN<br />
        Player UUID
    </div>
</div>